apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    path: /var/nfs/mongodb
    server: 192.168.99.1