apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    app: mongodb
spec:
  volumes:
    - name: mongodb-storage
      persistentVolumeClaim:
       claimName: mongodb-claim
  containers:
    - name: mongodb-container
      image: mongo:3.4
      ports:
        - containerPort: 27017
          name: "mongodb-server"
      volumeMounts:
        - mountPath: "/data"
          name: mongodb-storage