apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
       claimName: postgres-claim
  containers:
    - name: postgres-container
      image: postgres:10.0
      ports:
        - containerPort: 5432
          name: "postgres-server"
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data/pgdata"
          name: postgres-storage
      env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: POSTGRES_PASSWORD
          value: "POSTGRES_IN_KUBERNETES"